### PR TITLE
Add observers for Thread and Reply models.

### PR DESCRIPTION
**Pull request by butschster**
This PR allow to group all model listeners into a separated logical classes.

### CODE REVIEW

**Comment by JeffreyWay** [comment]
Thanks for this. It's well done, but let's keep things simple for now. If the number of observers grow, I'll reopen and merge this PR.

**Comment by butschster** [comment]
@JeffreyWay How can i attach commit with fix for unit tests in this PR?

**Comment by JeffreyWay** [comment]
You don't need to create any unit tests. This functionality is already covered under the main feature tests.

**Comment by butschster** [comment]
https://github.com/butschster/council/commit/01ab99e1d0c4a1673cab899a3aca5f76bce0f553

**Pull request closed without merging**
