### PR TITLE
WIP: Add realtime UI features using WebSockets

### PR DESCRIPTION
**Pull request by jorgenb**
This PR adds various realtime features to the app using either Pusher or Redis with Laravel Echo Server. Should be considered WIP, but if there is sufficient interest it could be further refined.

* Supports either Pusher or Laravel Echo Server
with Redis.
* A user must be logged in to use the features.

* Displays a list of online users in the sidebar.
* Displays a list of users viewing a thread in
the sidebar.
* Show who is typing when viewing a thread.
* Automatically updates the thread with a new
reply when Laravel fires \App\Events\ThreadReceivedNewReply

See readme.md for instructions on configuring.

## Issues that need to be resolved

* When a signed-in user leaves one part of the forum for another, for example by clicking a link, they also leave any presence channels they have joined and then "re-join" when the page reloads. This causes the list of online users and list of users viewing a thread to "flicker".
* The list of online users lists all users. Probably not ideal with many users.

## Other

* Should we have a channel for guests?

### CODE REVIEW

**Comment by JeffreyWay** [comment]
Thanks! I'll try to work through this PR soon. :)

**Comment by jorgenb** [comment]
Checks are failing due to the recent upgrade to 5.6. Laravel 5.6 uses the same version of `pusher/pusher-php-server` as 5.5 so it should be easy to resolve.

**Comment by jorgenb** [comment]
@JeffreyWay Do you want to introduce WebSockets to the forum? If so, I can find time sometime next week to rework this PR into something more production ready, although it would be nice to know which features you would be willing to accept?

- Supports either Pusher or Laravel Echo Server with Redis.
- A user must be logged in to use the features.
- Displays a list of online users in the sidebar.
- Displays a list of users viewing a thread in the sidebar.
- Show who is typing when viewing a thread.
- Automatically updates the thread with a new reply when Laravel fires \App\Events\ThreadReceivedNewReply

**Comment by jorgenb** [comment]
We should have a test to back up using `$this->reply->path()` in `ThreadReceivedNewReply` if we go with using this method to generate the channel name.

**Pull request closed without merging**
