### PR TITLE
Set default string length for Schema

### LINKED ISSUE #10: Error "key was too long" while migrating
On MySQL database server older than 5.7.7 `php artisan migrate` generates error "key was too long". 

To solve this you need to add line: `\Schema::defaultStringLength(191);` to AppServiceProvider@boot.

### PR DESCRIPTION
**Pull request by highsolutions**
This commit fixes error "key was too long" while migrating database on MySQL database server older than v5.7.7.

More explanations here: https://laravel-news.com/laravel-5-4-key-too-long-error

### CODE REVIEW

**Comment by highsolutions** [comment]
Resolves #10

**Comment by m1guelpf** [comment]
@highsolutions This is not a bug of this project, it's a problem with your setup. This shouldn't be added by default to any project, it should be something developers add if they have older DB versions. Also, this has been PR'd lots (https://github.com/laravel/laravel/pull/4532, https://github.com/laravel/laravel/pull/4505, https://github.com/laravel/laravel/pull/4183, https://github.com/laravel/laravel/pull/4159, https://github.com/laravel/laravel/pull/4158, https://github.com/laravel/laravel/pull/4488) and Taylor has decided to keep this out, so I believe we should do the same.

**Comment by highsolutions** [comment]
That's why @m1guelpf I wrote in corresponding issue that maybe better solution is write it only in troubleshooting section of README. But @JeffreyWay also said that he want to make as easy installation as possible and this is just one line that not harm anyone, and help some folks with older configuration.

**Comment by JeffreyWay** [comment]
I'm going to close this for now, in favor of a future Troubleshooting section in the docs. Thanks, though!

**Comment by highsolutions** [comment]
My pleasure, @JeffreyWay :).

**Pull request closed without merging**
