### PR TITLE
Rendering purified body HTML in profile activities

### PR DESCRIPTION
**Pull request by tykus**
Activity subjects' `body` data has been purified, so it is okay to unescape the body in each of the activities.

### CODE REVIEW

**Comment by tykus** [comment]
Resolves #22

**Comment by Douglasdc3** [comment]
Not sure why the empty lines are gone. Might want to check your editor settings to make sure to end files with an empty line.

**Comment by JeffreyWay** [comment]
@tykus, thanks so much for the pull request. Just a quick note to always ensure that you don't include miscellaneous changes/formatting in your PR that aren't related to the main fix you're providing. In this case, that would be the removal of the empty lines. No worries, though. 

Thanks again!

**Comment by tykus** [comment]
Editor issue... thanks!

**Pull request merged**
