### PR TITLE
[ wip ] — Style the users profile page

### PR DESCRIPTION
**Pull request by jonsugar**
This PR is a response to @JeffreyWay who asked for a pull request that styled the user profile page in the Laracasts video https://laracasts.com/series/how-to-manage-an-open-source-project/episodes/20.

🚨 **Note** this is **work in progress**.
- there are a couple of tests to fix.
- there are a couple of tests to implement.

Having said that, I think its in a relatively good place. @JeffreyWay you are free to merge if you think its _good enough_ for you to work with.

⚠️ Note that in  `.resources/assets/sass/_timeline.scss` there are a small number of styles for the timeline that can't be implemented via tailwind yet. At least I couldn't work out how 🤷‍♂️ 

**Features**
- Style the user activity following existing Council design precedence.
- On all activities show the amount of XP gained.
- On reply created activity show the number of favorites gained and if the reply is marked as the best answer.
- On thread created activity show the number of replies submitted.
- Paginate the profile activity using Vue and existing pagination component.

**Future Work**
1. Style the avatar upload section, potentially using Vue to make the interaction better.

screenshot-2018-2-19 council

### CODE REVIEW

**Comment by fshequin** [comment]
Jon,

I was just about to redo a set of commits and do this....you beat me to it.

One thing I see you may have not gotten to yet is this for the avatar form and it's file upload button:

https://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/

I used this method successfully and it seems to work well, you might consider this for the avatar upload button, looks like this:

image

Regards, Fred Shequine

**Comment by jonsugar** [comment]
@fshequin,

Thanks for the pointer regarding the file upload. I will check it out. 

In case you were considering not making a pull request, I think you should! I for one would like to compare different approaches to the same problem.

**Comment by JeffreyWay** [comment]
Looking good, @jonsugar! Nice work. I'm happy to merge this whenever you're ready. I can finish up any loose ends if you need. Just say the word, and we'll merge.

**Comment by jonsugar** [comment]
Okay, Go for it! Just a heads-up... as I mentioned, the the styles for the timeline are contained in a sass file. Some can be migrated into the blade templates but some are problematic. The ::before and ::after were giving me grief.

**Comment by jonsugar** [comment]
oops... Reopening

**Comment by jonsugar** [comment]
Okay, @JeffreyWay Go for it! 

Just a heads-up... as I mentioned, some of the styles for the timeline are contained in a sass file. The `:before content` hack specifically.

**Comment by jonsugar** [comment]
Okay, @JeffreyWay this is ready to merge 😁.

**Comment by fshequin** [comment]
@jonsugar , You went so far beyond what I had done, I really can't add anything to your great efforts. The only thing I was interested in seeing get added was the Avatar upload button using the css label technique for file upload inputs. This technique among many is indicted as the best way to go for styling file inputs by Chris Coyer over at CSS Tricks. I generally look there first for best methods for styling stuff. 

Great Job by the way!

Kind Regards, Fred Shequine

**Comment by JeffreyWay** [comment]
@jonsugar - I don't see `.resources/assets/sass/_timeline.scss` as part of your PR. Is that still applicable?

**Comment by JeffreyWay** [comment]
I'll get this finished up and merged today. A few missing pieces, but shouldn't take long.

Thanks!

**Pull request merged**
