### PR TITLE
Reputation points refactor

### LINKED ISSUE #87: [Discussion] Moving reputation points to council.php config file?
I think it would be easier and more logic for the average user to have all the configurable data in the same place.

@JeffreyWay and everyone else: how do you feel about it? Does this approach have any real downside?

### PR DESCRIPTION
**Pull request by MattMangoni**
Moved reputation points declaration to council.php config file and gain/lose methods to the HasReputation trait. I obviously refactored the related tests as well :)

Fix #87

### CODE REVIEW

**Comment by deframe** [comment]
Looks good but you should consider adding a getter method and something like `clearReputation()` to the trait. Abstracting that functionality will make it easy to change the implementation in the future, e.g. logging & calculating reputation rather than directly referencing a property on the model.

Also, app/Reputation.php can be deleted.

**Comment by MattMangoni** [comment]
@deframe I left it just because @JeffreyWay always said he wanted to use a dedicated table to handle that at some point, but yeah, there's no point in leaving an empty file there.

**Comment by MattMangoni** [comment]
Removed Reputation.php and added clear method to the Trait.
Still no getter though, since I don't think it would be necessary as soon as we have it in the user table. If you guys really think it's something we already need, I'll go ahead and do it :)

**Comment by if4lcon** [comment]
Nice job 👍

**Pull request merged**
