### PR TITLE
Fix clearing WYSIWYG editor after second reply

### PR DESCRIPTION
**Pull request by highsolutions**
Commit adds event handling for `input` event from `Wysiwyg` component in `NewReply` component to reset `completed` flag. Without this, when user is replied to this same thread twice (and more) without refreshing browser, editor hasn't cleared, because flag `completed` was set to `true` after first time and watcher hadn't see change.

Event handler just resets flag `completed` and after each reply, editor's content will be cleared.

PS. app.js is added, because it would be inconsistent otherwise. However it is not a good practice to keep assets in repository => generated unnecessary merge conflicts.

### CODE REVIEW

**Comment by highsolutions** [comment]
Issue https://github.com/JeffreyWay/council/issues/16.

**Comment by highsolutions** [comment]
Resolves #16

**Comment by JeffreyWay** [comment]
Decided to go with the #55 approach instead. Thanks for this though!

**Comment by highsolutions** [comment]
#55 is better solution than ours. We've just fix the bug we encounter, not thinking that this can be done better and cleaner. Lesson learned ;).

**Pull request closed without merging**
