### PR TITLE
using widgets concept.

### PR DESCRIPTION
**Pull request by imanghafoori1**
More parts of the can be widgetized and get benefit of caching.
for example list of threads, etc

### CODE REVIEW

**Comment by bambamboole** [comment]
@imanghafoori1 it would be nice if you could this describe a bit further.

**Comment by imanghafoori1** [comment]
we have an stand alone widget now which can be included in any view like a static partial.
The controller is not responsible for providing it with data.
It knows how to provide data for itself and it's out put is cached.
It does not query database and render partial each and every time. It caches the output html for later use.

**Comment by concept-core** [comment]
Looked at your PR but I kinda dislike the idea of having widget views in the app folder.
For any new dev using this project, it could make things more difficult than it should be.

The enhancement itself is something that I find interesting.

**Comment by JeffreyWay** [comment]
I think this PR is good, but I want to hold off until we have more of a reason to justify this setup. I'll return to it down the line if we expand enough to warrant it. Thanks!

**Pull request closed without merging**
