### PR TITLE
Prevent Form Submission - resolves #116

### LINKED ISSUE #116: [Bug] Updating a reply ends up with a full postback.
When we update a reply, the reply updates correctly, but it also submits the form.

### PR DESCRIPTION
**Pull request by ruman63**

### CODE REVIEW

**Comment by concept-core** [comment]
Are you sure you want to add the changes to the public files? ( css and js ? )
@JeffreyWay maybe add those files to the gitignore and add the npm command to the `InstallCommand`?

**Comment by ruman63** [comment]
yeah! sure, done.

**Comment by ruman63** [comment]
Hey @concept-core, I'm not sure if I messed up something. I did a soft reset to to the beginning of branch. Discarded the public assets and made a commit. Then, I did a force push. Is it the right way? Is there another better way? Have I messed up something?

**Comment by concept-core** [comment]
@ruman63 Do you miss any other changes now?
Or is the change that is waiting now the only change that is needed?

**Comment by ruman63** [comment]
Nope, I'm not missing any changes but I've lost previous commits (not an issue). I was just asking if there is another way so that ( in future ) I don't lose previous commits?

**Comment by concept-core** [comment]
I am not sure if there is a way to do that.
Normally I won't commit public css and js files.

**Comment by ruman63** [comment]
@concept-core Thanks a lot for your replies. Well, my question was, I had already committed public assets in a flow `git add .`, Then i was asked to remove those files from this PR. Was it a correct way to do so, what I did? I don't have very good knowledge of git. I was wondering if I made some mistake, it seemed like as if I got around this, maybe it wasn't the proper way ( I suspect there must be other better ways too ). Anyways, thanks!

**Pull request merged**
