### PR TITLE
Thread body mention

### PR DESCRIPTION
**Pull request by if4lcon**
Notify mentioned users in thread body

### CODE REVIEW

**Comment by m1guelpf** [comment]
@if4lcon Maybe add some tests?

**Comment by if4lcon** [comment]
@m1guelpf why not 👍 I'm outside now I'll do it later

**Comment by if4lcon** [comment]
@JeffreyWay I know you don't like this approach maybe I can change it to something else ?

**Comment by JeffreyWay** [comment]
@if4lcon I haven't had a chance to go through this PR yet. I'll try to get it done this week.

**Comment by if4lcon** [comment]
@JeffreyWay thanks mate I really enjoyed working in the project .. I like your refactored version always the best  👌 .. I need to watch a few Events episodes in Laracast  😆

**Pull request merged**
