### PR TITLE
Add initial User administration with account suspension

### PR DESCRIPTION
**Pull request by jonsugar**
This PR addresses [Issue #86 ](https://github.com/JeffreyWay/council/issues/86)

This is an initial attempt at adding a user administration section to the forum. It is intentionally limited to the following: 

**Administration Section**
- Scaffolding for the User admin section
- A list of current users (no sorting or pagination)
- The ability to suspend a user.
- Highlights administrators within the list of users.
- Links out to the list of users threads.

**Forum Section**
- Suspended users are prevented from creating new threads.
- Suspended users are prevented from replying.

There is a lot of scope for more features (for example,  optionally preventing suspended users from deleting their replies or fully removing users) but due to the already large number of changes, I decided it was better to make a PR with a smaller feature set.

**Notes/Issues**
- I am not totally happy with how the suspension middleware and authorization gates interact. 
- I think there are opportunities to introduce more Vue components for a better user experience.
- I would much prefer a simple list of users with a modal popup that contains the admin functions but I felt this would make the PR even bigger—an enhancement maybe.

All in all this PR might not be ready for merging even though the features it introduces are complete and tested. It may require tweaks and changes to make it better.

I'm open to suggestions!

### CODE REVIEW

**Comment by stefanbauer** [comment]
For me **personally**, this PR has too much changes not related to "Add initial User administration with account suspension". There are too much things happening here. For instance:

- Minor changes that has nothing to do with this PR
  - https://github.com/JeffreyWay/council/pull/132/files#diff-646a4842abf9023c975a9a1658a68b0a
  - https://github.com/JeffreyWay/council/pull/132/files#diff-5c8219e185e7565d81ff992d98aba0c8 
- Applying styles in files that has nothing to do with that PR
  - https://github.com/JeffreyWay/council/pull/132/files#diff-3bb62ddae5006563c6697274e326924c (replacing " with ')

**Comment by jonsugar** [comment]
@stefanbauer thanks for your feedback in [this comment](https://github.com/JeffreyWay/council/pull/132#issuecomment-361473277), you raised some valid points. I have reverted the changes you specifically mentioned and found some other similar ones. 

I did keep the refactor of the `app/Exceptions/ThrottleException` processing from `app/Exceptions/Handler.php` into the render method of the class its self as I think this is still valid.

The result of these changes are a couple of files removed from the PR and less changes in the diffs to look through in some of the other files. 

Good catch 👍

**Comment by stefanbauer** [comment]
@jonsugar yeah saw your changes. much cleaner now :) thanks!

**Comment by MattMangoni** [comment]
TravisCI check is failing, but only for PHP 7.2.

You should definitely check it out though: 
https://travis-ci.org/JeffreyWay/council/jobs/335113744

That's a big PR, good work :)

**Comment by jonsugar** [comment]
@MattMangoni Yes, I was in two minds whether I should split it into two separate PRs but in the end, I thought just listing the users with no actual admin functionality was wrong. With hindsight I was wrong.

Interestingly, the travis-ci failure is a weird one. I installed PHP7.2 to test it. Sure enough, the test failed. I ran it again it passed. I can't seem to make it fail again. I'm not sure whats happening there.

**Comment by rixgov** [comment]
I had this EXACT problem earlier.  Turn's out PHPunit can't read the HTML output correctly.  Look at "O'Keaf" the last name of your user.  It's there, the the apostrophe is converted to an HTML version, thus it doesn't match up exactly.  It's a unwanted failure, and I'm not sure how to guard against that error, I have resorted to simple re-running the suite.

**Comment by MattMangoni** [comment]
@rixgov Nice! Thanks for investigating on that :D

**Comment by nycofox** [comment]
I also had issues with apostrophes in the tests, but after some feedback on the Laracasts forums I got the solution by using the e() function.

`$this->assertEquals(e("you're cool"), $varOnPage);`

**Comment by jonsugar** [comment]
Closing for now…

I may resubmit this PR once the design branch has been merged into master and I have made all appropriate changes.

**Pull request closed without merging**
